### ISSUE TITLE
Back and feet suddenly stopped working in normal idle set

### ISSUE THREAD

**Issue by reffeirhcs** [Selindrile/GearSwap#62]
This week, my feet and back slots randomly stopped working for WHM and BRD.

For WHM, from the moment I change jobs, only the back and feet slots do not work, everything else is fine.

For BRD, after changing jobs, the idle set is correct, but if I cast a song in town, the boots stay in midcast and do not go back to idle.

I have searched long and hard for solutions to this online, and while a few people seem to have had a similar issue, I could not find an explanation as to why this happens.

[Mightylovers_Whm_Gear - Copy.txt](https://github.com/Selindrile/GearSwap/files/7892070/Mightylovers_Whm_Gear.-.Copy.txt)

[Sachmiel_Brd_Gear - Copy.txt](https://github.com/Selindrile/GearSwap/files/7892074/Sachmiel_Brd_Gear.-.Copy.txt)

**Comment by Selindrile** [comment]
1.) It's never random, there's always a reason.
2.) You'll get real time back and forth answers on my discord, a much better way to ask for help: https://discord.gg/ug6xtvQ
3.) It's just an educated guess from the information you've given so far, but the fact that you specifically mention town, and the feet slot, I'm guessing you may not realize that sets.Kiting takes precedence over normal idle sets in town, and the back slot may be due to sets.DayIdle or sets.NightIdle and the time of day, before searching long and hard for online, consider really taking a close look at the files themselves, the DayIdle and NightIdle sets should've been pretty self evident, and even if the kiting set isn't as obvious, removing gear that one doesn't own from the sets would've prevented this issue as if sets.Kiting was empty, it would've been using your normal idle set feet slot instead.
