### ISSUE TITLE
Hachirin-no-Obi not equipping under any circumstances on WHM

### ISSUE THREAD

**Issue by reffeirhcs** [Selindrile/GearSwap#63]
Apologies for posting another issue for something that is likely an easy fix, but I have no idea what to do.

Even though Hachirin-no-Obi is the waist equipment in ALL of my cure sets regardless of weather, every time I cast a cure the lua equps Embla Sash for some reason, even if sublimation is not active.

It appears to me as though gearswap thinks I don't even own the item, which of course I do.

Embla sash is only included in my lua for sublimation buff active, precast, and enhancing magic midcast and is found nowhere in any cure set so I am quite confused as to why this is happening. 

Any help would be greatly appreciated. Everything else in the lua seems to be working fine (thank you for the help before with the idle boot situation)
[Mightylovers_Whm_Gear - Copy.txt](https://github.com/Selindrile/GearSwap/files/7993598/Mightylovers_Whm_Gear.-.Copy.txt)
.

**Comment by Selindrile** [comment]
You're most likely testing on yourself, Embla Sash  is in precast so that is equipping first, midcast is attempting to equip Gishdubar Sash because sets.Self_Healing is applied over the cure set when curing yourself, which you probably don't have, so Embla Sash remains equipped.

Remember, one step in troubleshooting is always to start from naked, and see if the set equips directly with "//gs equip setname", that would've told you that Embla Sash wasn't actually the issue, another important thing is to actually go over all of the file, and make sure you take out things you don't have, etc, and read the names of sets, I imagine if you'd looked at "Self_Healing" you'd probably have figured out it was trying to equip that.
